import { Box, Typography } from '@mui/material';
const styles = {
  secondTitle: {
    textAlign: 'center',
    color: '#7A7A7A',
    fontSize: { md: 24, xs: 14 },
    fontFamily: 'Candal',
    fontWeight: '400',
    textTransform: 'capitalize',
    wordWrap: 'break-word',
    width: { xl: '1092px' },
    m: { md: '0 auto 60px', xs: '0 auto 20px' },
  },
  wrap: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    flexWrap: 'wrap',
    gap: { md: '40px', xs: '14px' },
    width: { md: 'auto', xs: '350px' },
    m: { md: '0 auto 100px', xs: '0 auto 20px' },
  },
  item: {
    fontFamily: 'Candal',
    alignItems: 'center',
    textAlign: 'center',
    display: 'flex',

    background:
      'linear-gradient(100deg, #1A1E28 30%, #1A1E28 53%, #3A140F 100%)',
    borderRadius: '26px',
    position: 'relative',
    padding: { md: '62px 28px', xs: '35px 21px' },
    width: { md: 'calc(33% - 30px)', xs: '100%' },
  },

  content: {
    width: '100%',
    color: '#fff',
    fontSize: { md: '36px', xs: 14 },
    fontFamily: 'Candal',
    fontWeight: '400',
    textTransform: 'capitalize',
    wordWrap: 'break-word',
    lineHeight: { md: '50px', xs: '30px' },
  },
  item1: {
    mb: { md: '60px', xs: '30px' },
  },
  content1: {
    width: '100%',
    color: '#fff',
    fontSize: { md: '24px', xs: 14 },
    fontFamily: 'Candal',
    fontWeight: '400',
    textTransform: 'capitalize',
    wordWrap: 'break-word',
    lineHeight: { md: '36px', xs: '21px' },
    textAlign: 'center',
  },
};

const list1 = [
  {
    content: `In addition to competing for block rewards through computing power on the TBC chain, miners will also obtain corresponding handling fees by confirming and verifying transactions. The transaction fee is linked to the volume of the transaction. The larger the transaction volume, the higher the transaction fee. In TBC's miner economic model, block rewards will decrease over time, and at the same time, as the number of users grows, the handling fee rate will be gradually reduced through "fee reduction" to adapt to the needs of more people's use. This is the exact opposite of the prevailing Ethereum rate situation.`,
  },
  {
    content: `Although the average transaction fee per transaction may be less than $0.001, the goal of TBC is to carry a large number of Web3 applications and users, so the number of transactions contained in each block will also be a large number of transactions generated by many applications, and the accumulated transaction procedures. The fee will also be considerable, and with the maturity of the application and the increase of users, the transaction fee per block will surpass the block reward within a few years and become the main source of income for miners.`,
  },
  {
    content: `The economic model of TBC is more likely to be combined with the most common C-side free and B-end charging model in reality, and will become one of the blockchain solutions that are most in line with and closest to the law of real development in reality.`,
  },
];
export const Fee = (props: any) => {
  return (
    <Box
      sx={{
        color: '#fff',
        h4: {
          color: '#F33000',
          fontSize: { md: '70px', xs: '24px' },
          textAlign: 'center',
          p: { md: '20px 0 60px', xs: '0 0 20px' },
          m: 0,
        },
        h6: { color: '#fff', fontSize: '18px', padding: '10px 0' },
        marginTop: '50px',
        p: { md: '0 50px 50px', xs: '0 20px 20px' },
        '.rImg': {
          position: 'absolute',
          right: '50px',
          top: '45px',
        },
      }}
    >
      <Typography variant="h4" gutterBottom sx={{}}>
        How TBC Runs Turing -Complete Smart Contracts
      </Typography>
      <Box sx={styles.secondTitle}>
        TBC has cutting-edge technical practice solutions with infinitely close
        to zero handling fees
      </Box>

      <Box>
        {list1.map((item, i) => {
          return (
            <Box sx={styles.item1}>
              <Box sx={styles.content1}>{item.content}</Box>
            </Box>
          );
        })}
      </Box>
    </Box>
  );
};
